title: "AR20386: Mathematics 2"
author: "Nick McCullen"  # The author of the book
logo: Figures/uob-logo.png
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/nickmccullen/AR20386_notes
  branch: main
  path_to_book: ""
html:
  use_repository_button: true
  use_issues_button: true
# Launch button settings
launch_buttons:
  notebook_interface        : classic  
  binderhub_url             : "https://mybinder.org" 
  
use_download_button              : true 
